### ISSUE TITLE
Fix GH Actions macOS builds.

### ISSUE THREAD

**Issue by floooh** [floooh/sokol-rust#13]
GH Actions now fails with:

```
 = note: Undefined symbols for architecture x86_64:
            "___isPlatformVersionAtLeast", referenced from:
                __sg_mtl_init_caps in libsokol-91c8d94baf7f5766.rlib(sokol_gfx.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

(see https://github.com/floooh/sokol-rust/actions/runs/5578442971/jobs/10192658739)

Not reproducible locally on M1 Macs.

It's related to the new use of `if (@available(...))` in the sokol headers to check for availability of macOS/iOS API features. Zig had the same problem, but there it was fixed by updating to the latest zig-0.11.0-dev version.

**Comment by samloeschen** [comment]
is there any workaround for this, currently?

**Comment by floooh** [comment]
Not that I know of. On M1 Macs it works, as well as 'native' builds on x86-64 Macs (e.g. not the Rust bindings). It seems to be a specific problem of building with the Rust toolchain on x64-64 Macs.

**Comment by samloeschen** [comment]
I'm running into this on my M2 mac actually! Happy to provide a test repo if that's helpful

**Comment by floooh** [comment]
Strange, can you check if `cargo run --example clear` from within the sokol-rust directory works for you?

E.g. on my M1 Mac this works. My system is:

- macOS 14.3.1 (23D60)
- Xcode 15.2
- clang --version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- xcrun --sdk macosx --show-sdk-path: ...SDKs/MacOSX14.2.sdk

Maybe the SDK version is too old? Because those functions that fail to link might have been added in a somewhat recent SDK version.

**Comment by floooh** [comment]
PS: did this PR fix the issue btw? https://github.com/floooh/sokol-rust/pull/24

**Comment by samloeschen** [comment]
apologies for the delay in reply; yes, that PR seems to have fixed it! it looks like i was implicitly using a different version of `cc` than the example clear which is what caused the problem.

**Comment by vrishk** [comment]
I'm still facing this issue on my local m1 mac - unsure if it is caused by something with my env. Do you know what it could be?

**Comment by floooh** [comment]
I have an 2021 M1 Mac with macOS 14.4.1.

Cargo and Rust versions:
```
cargo --version
cargo 1.77.0 (3fe68eabf 2024-02-29)
rustc --version
rustc 1.77.0 (aedd173a2 2024-03-17)
```

There have been some recent changes which require 1.77 (the use of C string literals).

Other then that I get 2 warnings which are known issues:

`warning: creating a mutable reference to mutable static is discouraged`

...but `cargo run --example cube` etc... works.

**Comment by vrishk** [comment]
I'm not sure, I have versions `1.77.2 (e52e36006 2024-03-26) on` each of them. I do see the warning you mention but it comes back with the error of:

```
Undefined symbols for architecture arm64:
            "___isPlatformVersionAtLeast", referenced from:
                __sg_mtl_init_caps in libsokol-a46ed52c83094c49.rlib(sokol_gfx.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there some setup I am missing? I've reinstalled xcode to make sure `TargetConditionals.h` was available but the `@available` function still seems to error out.

**Comment by floooh** [comment]
Ah ok, this error is unrelated to the Rust toolchain. It must be something about the macOS SDK or Xcode toolchain version.

Can you paste the output of the following commands here?

`xcrun --sdk macosx --show-sdk-path`

(for reference, I get: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk`)

...and `clang --version`, where I get:

```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by vrishk** [comment]
Makes sense. 

I get `xcrun --sdk macosx --show-sdk-path`:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk
```
and `clang  --version`:

```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
As expected, older versions. I did re-download xcode as I didn't seem to have it earlier (prob deleted it due to space constraints at some point) - so I'm assuming that this is the latest version of each: Xcode Version 14.2 (14C18) and SDK 13.1. 

On the code, that makes sense. I just commented out the section of `sokol_gfx.h/__sg_mtl_init_caps(void)` with the preprocessor check (https://github.com/floooh/sokol/blob/4534e02d6c83e23fa212ac29c1fd90d8a22f5419/sokol_gfx.h#L11623 to https://github.com/floooh/sokol/blob/4534e02d6c83e23fa212ac29c1fd90d8a22f5419/sokol_gfx.h#L11631) and it started working as expected. I tried increasing the version to 127000 and 130000 but it did not help.

Although I have a temporary fix, it would be nice to figure this out, if possible - it seems like a deeper issue.

**Comment by floooh** [comment]
Btw, could you check if this non-Rust project builds for you, or whether you see the same errror there?

https://github.com/floooh/pacman.c

Build instructions are in the readme, you just cmake in addition to the Xcode command line tools.

Thanks!

**Comment by vrishk** [comment]
Yep, just tried it, it build fine and I can run it.

On the @available case, do you think @available only when used with a version higher than the current macos version seems to give an error? I just commented out the only case where it is used with 13.0 rather than just 12.0 and it seems to be compiling fine.

It could just be that if the macos version is lower than 13, this issue crops up?

**Comment by floooh** [comment]
> It could just be that if the macos version is lower than 13, this issue crops up?

That would be the only reason that makes sense yeah. But then it's still strange that a plain C project works.
